version: '3'
services:
  mailman:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mailman
    image: mailman
    restart: always
    ports:
      - "8002:8000"
    volumes:
      - /var/log/mailman:/var/log/mailman
    env_file:
      - .env
